config/routes.rb
Rails.application.routes.draw do
  post 'users/save_user'
  get 'users/create_user'
  get 'users/take_test'
  post 'users/submit_test'

  root 'users#create_user'

  post 'questions/display_test'

  resources :questions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :question, presence: true
	validates :op1, presence: true
	validates :op2, presence: true
	validates :op3, presence: true
	validates :op4, presence: true
	validates :correct, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def new
		@question = Question.new
	end

	def edit
		@question = Question.find(params[:id])
	end
	def create
		
		#render plain: params[:question].inspect
		@question = Question.new(question_params)
		
		if @question.save
			redirect_to @question
		else
			render 'new'
		end
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		redirect_to questions_path
	end

	def update
  		@question = Question.find(params[:id])
 
  		if @question.update(question_params)
    		redirect_to @question
  		else
    		render 'edit'
  		end
	end
	def show
		puts '-------------'
		puts params.inspect
		@question = Question.find(params[:id])
	end

	def index
		@questions = Question.all
	end

	

	def display_test
	end


	private
		def question_params
			params.require(:question).permit(:question,:op1,:op2,:op3,:op4,:correct)
		end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :verify_authenticity_token  

	def create_user
		@user = User.new
	end

	def save_user
		@user = ""
		if user_save_params.present?
			# User.create(user_save_params)
			@user = User.new
			@user.first_name = user_save_params[:first_name]
			@user.last_name = user_save_params[:last_name]
			@user.date_of_birth = user_save_params[:date_of_birth]
			@user.save
		end
		redirect_to users_take_test_path(:user_id => @user.id)
	end

	def take_test
		@questions = Question.all
		@question_count = @questions.count
		@users = User.all
		#puts 'params',params.inspect
		@user_id = params[:user_id]
	end

	def submit_test

		#puts 'params',params.inspect
		#Answer.create(user_save_params)
		#render plain: params[input_values].inspect
		
		@input_values=params[:input_values]

		@user_id = params[:user_id]
		#this is for destroying the table entries of the previous user
		Answer.where(user_id: @user_id).destroy_all

		@input_values.each  do |k,v|
			@answer = Answer.new
			@answer.user_id = @user_id
			@answer.question_id = k
			@answer.input_answer = v
			@answer.save
		end
		@questions = Question.all
		total_question= @questions.count
		count = 0
		@all_answer = Answer.where(:user_id => @user_id)
		@all_answer.each do |answer|
		end
		for i in 1..total_question
			@question = Question.find_by_id i
			@answer = @all_answer.find_by_question_id i
			if @question.correct == @answer.input_answer
				count = count + 1
			end
		end
		puts "total question"
		render :text =>"#{count} out of #{total_question}"
		


	end

	private
		def user_save_params
			params.require(:user).permit(:first_name,:last_name, :date_of_birth)
		end

		# def submit_test_params
		# 	params.permit(:first_name,:last_name, :date_of_birth)
		# end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@question.errors.count,"error")%> prohibited this question from being saved
      </h3>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%=msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <p>
    
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </p>
 
  <p>
    <%= f.radio_button :correct,1 %>
    <%= f.label :"Option 1" %><br>
    <%= f.text_field :op1 %>
  </p>

  <p>
    <%= f.radio_button :correct,2 %>
    <%= f.label :"Option 2" %><br>
    <%= f.text_field :op2 %>
  </p>

  <p>
    <%= f.radio_button :correct,3 %>
    <%= f.label :"Option 3" %><br>
    <%= f.text_field :op3 %>
  </p>

  <p>
    <%= f.radio_button :correct,4%>
    <%= f.label :"Option 4" %><br>
    <%= f.text_field :op4 %>
  </p>

  
  

 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/edit.html.erb
<h1>Edit the question</h1>
 
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>List of questions</h1>
 <%= link_to 'Add a question', new_question_path %>
<table>
  <tr>
    <th>Question id</th>
    <th>Question</th>
    <th>Option 1</th>
    <th>Option 2</th>
    <th>Option 3</th>
    <th>Option 4</th>
    <th> Correct answer</th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.question %></td>
      <td><%= question.op1 %></td>
      <td><%= question.op2 %></td>
      <td><%= question.op3 %></td>
      <td><%= question.op4 %></td>
      <td><%= question.correct %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
      <td><%= link_to 'Edit', edit_question_path(question)%></td>
      <td><%= link_to 'Destroy',question_path(question), method: :delete, data:  {confirm: 'Are you sure' }%></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>Add a new question</h1>
 
<%= render 'form' %>

app/views/questions/show.html.erb
<p>
<strong>Question</strong><br>
<%= @question.question %>
<br><strong>Option 1 :</strong>
<%= @question.op1 %>
<br><strong>Option 2 :</strong>
<%= @question.op2 %>
<br><strong>Option 3 :</strong>
<%= @question.op3 %>
<br><strong>Option 4 :</strong>
<%= @question.op4 %>
<br><strong>Correct Answer</strong>
<%= @question.correct %>

<br><%= link_to 'Back', questions_path %>
<%= link_to 'Edit', edit_question_path(@question) %>

app/views/users/create_user.html.erb
<%= form_for @user, url: {action: "save_user"}, html: {class: "nifty_form"} do |f| %>
   <p>
    <%= f.label :"First Name" %><br>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :"Last Name" %><br>
    <%= f.text_field :last_name %>
  </p>

   <p>
    <%= f.label :"Date of Birth" %><br>
     <%= f.date_select :date_of_birth, :start_year => 1985,:order => [:day, :month, :year] %>
   </p>
   <p>
    <%= f.submit "Submit and start the Test" %>
   </p>
  
<% end %>

app/views/users/take_test.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>

function save_result(){
	var querry='.q_';
	var i;
	var answer = "answer";
	var z1 = 'input[name=answer';
	var z2;
	var input;
	var user_id = <%= @user_id %>
	var input_values={};
	var z3= ']:checked'
	for (i = 1;i <= <%= @question_count %> ;i++)
	{
	querry += i.toString();
	z2 = (i).toString();
	input=$(z1+z2+z3, querry).val();
	input_values[i]=parseInt(input);
	console.log(input);
	querry ='.q_';
	}
	// $.post('/users/submit_test', function(data, status){
 //        alert("Data: " + data + "\nStatus: " + status);
 //    });

	$.post('/users/submit_test', {input_values:input_values,user_id:user_id},function(data,status){
        alert("Data: " + data + "\nStatus: " + status);
    });
}

</script>
<% user = @users.find_by_id @user_id%>
<%= "Welcome " + user.first_name + " " + user.last_name + "\n"%>
<%= "Lets Begin the Quizzz" %>
<%= "Your id: " + @user_id %>
<% id=@user_id %>
<table>
<% @questions.each do |question| %>
    <% qid = "q_"+question.id.to_s %>
    <% answer = "answer" + question.id.to_s %>
    <tr class="<%= qid%>">
      <td><%= question.question %></td><br>
      <td><%= radio_button_tag answer, '1'  %><%= question.op1 %></td><br>
      <td><%= radio_button_tag answer, '2'  %><%= question.op2 %></td><br>
      <td><%= radio_button_tag answer, '3'  %><%= question.op3 %></td><br>
      <td><%= radio_button_tag answer, '4'  %><%= question.op4 %></td><br>
    </tr>
<% end %>
</table>

<input type="button" name="get_result" value="Save and get result" onclick="save_result();">